=== HaseebAnjumDev/BookTok-Tech-Shifting/xml/books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:simpleType name="BookIdType">
    <xs:restriction base="xs:string">
      <xs:pattern value="([0-9]+|BK-[0-9]{4})"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="LanguageCodeType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-z]{2}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="CurrencyCodeType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{3}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="IsbnType">
    <xs:restriction base="xs:string">
      <!-- Accepts ISBN-10/13 with optional hyphens (loosely constrained) -->
      <xs:pattern value="[0-9Xx-]{10,17}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="RatingType">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="5"/>
      <xs:fractionDigits value="1"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="FormatType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Paperback"/>
      <xs:enumeration value="Hardcover"/>
      <xs:enumeration value="Ebook"/>
      <xs:enumeration value="Audiobook"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="AuthorType">
    <xs:sequence>
      <xs:element name="firstName" type="xs:string"/>
      <xs:element name="lastName" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="PriceType">
    <xs:simpleContent>
      <xs:extension base="xs:decimal">
        <xs:attribute name="currency" type="CurrencyCodeType" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="TagsType">
    <xs:sequence>
      <xs:element name="tag" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="BookType">
    <xs:sequence>
      <xs:element name="title" type="xs:string"/>
      <xs:element name="author" type="AuthorType"/>
      <xs:element name="genre" type="xs:string"/>
      <xs:element name="format" type="FormatType"/>
      <xs:element name="language" type="LanguageCodeType"/>
      <xs:element name="isbn" type="IsbnType"/>
      <xs:element name="publisher" type="xs:string" minOccurs="0"/>
      <xs:element name="publishDate" type="xs:date"/>
      <xs:element name="pages" type="xs:positiveInteger" minOccurs="0"/>
      <xs:element name="price" type="PriceType"/>
      <xs:element name="rating" type="RatingType" minOccurs="0"/>
      <xs:element name="coverImage" type="xs:string" minOccurs="0"/>
      <xs:element name="description" type="xs:string" minOccurs="0"/>
      <xs:element name="tags" type="TagsType" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="id" type="BookIdType" use="required"/>
  </xs:complexType>

  <xs:element name="catalog">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="book" type="BookType" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="updated" type="xs:date" use="optional"/>
    </xs:complexType>

    <xs:unique name="uniqueBookId">
      <xs:selector xpath="book"/>
      <xs:field xpath="@id"/>
    </xs:unique>

    <xs:unique name="uniqueIsbn">
      <xs:selector xpath="book"/>
      <xs:field xpath="isbn"/>
    </xs:unique>
  </xs:element>

</xs:schema>

=== HaseebAnjumDev/BookTok-Tech-Shifting/xml/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Validate with backend/validate-books-xml.ps1 -->
<catalog
	updated="2026-01-04"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="books.xsd">

	<book id="1">
		<title>Fourth Wing</title>
		<author>
			<firstName>Rebecca</firstName>
			<lastName>Yarros</lastName>
		</author>
		<genre>Fantasy</genre>
		<format>Hardcover</format>
		<language>en</language>
		<isbn>978-1-64937-404-2</isbn>
		<publishDate>2023-05-02</publishDate>
		<price currency="USD">18.99</price>
		<rating>4.8</rating>
		<coverImage>../assets/images/Fourth Wing.jpg</coverImage>
		<description>BookTok favorite: Fourth Wing by Rebecca Yarros.</description>
		<tags>
			<tag>bestseller</tag>
			<tag>trending</tag>
			<tag>featured</tag>
		</tags>
	</book>

	<book id="2">
		<title>The Midnight Library</title>
		<author>
			<firstName>Matt</firstName>
			<lastName>Haig</lastName>
		</author>
		<genre>Fiction</genre>
		<format>Paperback</format>
		<language>en</language>
		<isbn>9780525559474</isbn>
		<publishDate>2020-09-29</publishDate>
		<price currency="USD">15.50</price>
		<rating>4.7</rating>
		<coverImage>../assets/images/The Midnight Library.jpg</coverImage>
		<description>Staff pick: The Midnight Library by Matt Haig.</description>
		<tags>
			<tag>staff-pick</tag>
			<tag>bestseller</tag>
			<tag>featured</tag>
		</tags>
	</book>

	<book id="3">
		<title>Lessons in Chemistry</title>
		<author>
			<firstName>Bonnie</firstName>
			<lastName>Garmus</lastName>
		</author>
		<genre>Non-Fiction</genre>
		<format>Hardcover</format>
		<language>en</language>
		<isbn>9780385547345</isbn>
		<publishDate>2022-04-05</publishDate>
		<price currency="USD">16.25</price>
		<rating>4.6</rating>
		<coverImage>../assets/images/Lessons In Chemistry.jpeg</coverImage>
		<description>Book club pick: Lessons in Chemistry by Bonnie Garmus.</description>
		<tags>
			<tag>book-club</tag>
			<tag>bestseller</tag>
		</tags>
	</book>

	<book id="4">
		<title>Pride and Prejudice</title>
		<author>
			<firstName>Jane</firstName>
			<lastName>Austen</lastName>
		</author>
		<genre>Romance</genre>
		<format>Paperback</format>
		<language>en</language>
		<isbn>9780141439518</isbn>
		<publishDate>1813-01-28</publishDate>
		<price currency="USD">9.99</price>
		<rating>4.9</rating>
		<coverImage>../assets/images/Pride and Prejudice.jpg</coverImage>
		<description>Classic: Pride and Prejudice by Jane Austen.</description>
		<tags>
			<tag>classic</tag>
		</tags>
	</book>

	<book id="5">
		<title>Project Hail Mary</title>
		<author>
			<firstName>Andy</firstName>
			<lastName>Weir</lastName>
		</author>
		<genre>Science Fiction</genre>
		<format>Hardcover</format>
		<language>en</language>
		<isbn>978-0-593-39556-1</isbn>
		<publishDate>2021-05-04</publishDate>
		<price currency="USD">19.99</price>
		<rating>4.9</rating>
		<coverImage>../assets/images/Project Hail Mary.jpg</coverImage>
		<description>New release highlight: Project Hail Mary by Andy Weir.</description>
		<tags>
			<tag>new</tag>
			<tag>sale</tag>
			<tag>featured</tag>
		</tags>
	</book>

	<book id="6">
		<title>Mindset</title>
		<author>
			<firstName>Carol S.</firstName>
			<lastName>Dweck</lastName>
		</author>
		<genre>Psychology</genre>
		<format>Paperback</format>
		<language>en</language>
		<isbn>9781400062751</isbn>
		<publishDate>2006-02-28</publishDate>
		<price currency="USD">14.00</price>
		<rating>4.5</rating>
		<coverImage>../assets/images/Mindset.jpg</coverImage>
		<description>Popular psychology: Mindset by Carol S. Dweck.</description>
		<tags>
			<tag>popular</tag>
		</tags>
	</book>

	<book id="7">
		<title>Clean Code</title>
		<author>
			<firstName>Robert C.</firstName>
			<lastName>Martin</lastName>
		</author>
		<genre>Tech</genre>
		<format>Paperback</format>
		<language>en</language>
		<isbn>978-0-13-235088-4</isbn>
		<publishDate>2008-08-01</publishDate>
		<price currency="USD">32.00</price>
		<rating>4.8</rating>
		<coverImage>../assets/images/Clean Code.jpg</coverImage>
		<description>Software craftsmanship staple: Clean Code by Robert C. Martin.</description>
		<tags>
			<tag>high-rated</tag>
		</tags>
	</book>

	<book id="8">
		<title>The Silent Patient</title>
		<author>
			<firstName>Alex</firstName>
			<lastName>Michaelides</lastName>
		</author>
		<genre>Mystery</genre>
		<format>Paperback</format>
		<language>en</language>
		<isbn>9781250301697</isbn>
		<publishDate>2019-02-05</publishDate>
		<price currency="USD">12.50</price>
		<rating>4.3</rating>
		<coverImage>../assets/images/The Silent Patient.jpg</coverImage>
		<description>Mystery thriller: The Silent Patient by Alex Michaelides.</description>
		<tags>
			<tag>unavailable</tag>
		</tags>
	</book>

</catalog>
